csr_ospf_router_id: 2.2.2.2
csr_ospf_interfaces:
  - interface: GigabitEthernet1
    ipv4: 10.0.12.2
    netmask: 255.255.255.0
    passive: false
    description: basic_netai P2P csr02 Gi1 to csr01 Gi1
  - interface: GigabitEthernet2
    ipv4: 10.0.23.2
    netmask: 255.255.255.0
    passive: false
    description: basic_netai P2P csr02 Gi2 to csr03 Gi2
  - interface: GigabitEthernet4
    ipv4: 10.0.0.25
    netmask: 255.255.255.0
    passive: true
    description: basic_netai lab cloud 10.0.0.0/24 (matches ansible_host)
